# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_final1', '0008_auto_20180126_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='shift_table_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable_final1.shift'),
        ),
    ]
