# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_final1', '0009_faculty_shift_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom_available',
            name='shift_table_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable_final1.shift'),
        ),
        migrations.AddField(
            model_name='faculty_subject',
            name='shift_table_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable_final1.shift'),
        ),
        migrations.AddField(
            model_name='lab_available',
            name='shift_table_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable_final1.shift'),
        ),
        migrations.AddField(
            model_name='semester_batch',
            name='shift_table_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable_final1.shift'),
        ),
        migrations.AddField(
            model_name='semester_classroom',
            name='shift_table_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable_final1.shift'),
        ),
        migrations.AddField(
            model_name='semester_lab',
            name='shift_table_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable_final1.shift'),
        ),
        migrations.AddField(
            model_name='subject_batch',
            name='shift_table_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable_final1.shift'),
        ),
        migrations.AddField(
            model_name='subject_no_student',
            name='shift_table_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable_final1.shift'),
        ),
    ]
