# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_final1', '0012_subject_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.BooleanField()),
                ('resource_id', models.IntegerField()),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final1.day')),
                ('faculty_subject_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final1.faculty_subject')),
                ('semester_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final1.semester')),
                ('shift_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final1.shift')),
                ('timeslot_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final1.timeslot')),
            ],
        ),
    ]
