# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_final1', '0013_temp_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_lab',
            name='descipline_course_table_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable_final1.descipline_course'),
        ),
    ]
